apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron_chromium
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - '-c'
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
